#!/gsc/bin/perl

use warnings FATAL => 'all';
use strict;
use GSCApp;
App->init;

use Path::Class;

my $fh1 = file('./run-start-end-dates.txt')->openr;
my %month;

# get the same time frame as gb-vs-month.txt
$month{$_} = []
    for (
        qw(2006-12 2007-01 2007-02 2007-03 2007-04 2007-05 2007-06 2007-07 2007-08)
    );

while ( scalar( my $line  = $fh1->getline)) {
    chomp $line;
    my ($start, $end, $diff, $fc) = split(/\t/, $line, 4);
    my $month = ( $start =~ /(^\d\d\d\d-\d\d).*/ )[0] or die;
    $month{$month} ||= [];
    push @{ $month{$month} }, $diff;
}
$fh1->close or die;

my $fh2 = file('./days-vs-month.txt')->openw or die;
$fh2->print("Month\tDays\n");
use List::AllUtils qw(sum);
for my $mon ( sort keys %month ) {
    my @all = @{ $month{$mon} };
#print "$mon\n";
    my $avg = scalar(@all) ? ( sum(@all) / scalar(@all) ) : 0;
    my $monx =  $mon . '-15';  # to make my R happy
    $fh2->print("$monx\t$avg\n");
}
$fh2->close or die;


